### PR TITLE
reset on GPIO0 after 10 seconds

### PR DESCRIPTION
**Pull request by danbates2**

### CODE REVIEW

**Comment by glynhudson** [comment]
Thanks, however, could you fix the conflict in `src.ino` ?

**Comment by danbates2** [comment]
Done, I think.

**Comment by glynhudson** [comment]
Not quite, not sure what's going on. It looks like the whole src.ino was slightly different. Must be whitespace. I've just fixed and merged.

**Comment by danbates2** [comment]
I did an auto-format!

**Comment by danbates2** [comment]
Once I've tested Jeremy's implementation I'll let you know.. The other pull
request has it contained and it compiles.. Just need to check it works for
this version of EmonESP on an actual esp device.

**Pull request merged**
