### PR TITLE
Update readme.md

### PR DESCRIPTION
**Pull request by danbates2**
added Flash Size change detail instruction

### CODE REVIEW

**Comment by danbates2** [comment]
Good to know. I'll try 4/4 SPIFFS for the ESP-12, and check out PlatformIO.
1/512k seems to be working for now.
Are the ESP-12 chips sensitive to heat and/or static? I'm wondering how I
could have possibly blown one yesterday.

On 20 Feb 2017 10:51, "Glyn Hudson" <notifications@github.com> wrote:

*@glynhudson* requested changes on this pull request.

The correct selection should be 4M (4M SPIFFS) for ESP-12 e.g Huzzah.
Highly recommend using PlatformIO over Arduino IDE, it's much easier. No
manual library, version management or settings needed.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/openenergymonitor/EmonESP/pull/21#pullrequestreview-22732620>,
or mute the thread

**Comment by jeremypoulter** [comment]
Also be aware that although 1/512k will 'work' OTA won't. For 1M flash you probably want 64 or 128k SPIFFS, but as @glynhudson says 4M (3M SPIFFS) is correct for the ESP-12 module.

**Comment by danbates2** [comment]
OK. So is it 4/4 SPIFFS or 4/3 SPIFFS?

**Comment by jeremypoulter** [comment]
screenshot 2017-02-20 14 20 14

4/3 SPIFFS

**Comment by danbates2** [comment]
Mind if I ask trouble shooting questions here? I’ve got intermittent error codes which I don’t understand. Sometimes it works, sometimes it doesn’t.

**Comment by glynhudson** [comment]
The forum would be more suitable to ask support questions. Happy to help on the forum...

**Comment by danbates2** [comment]
K. Great.

**Pull request closed without merging**
