### PR TITLE
How to upload pre-compiled binaries readme update

### PR DESCRIPTION
**Pull request by danbates2**

### CODE REVIEW

**Comment by jeremypoulter** [comment]
You shouldn't add the pre-compiled binaries. GitHub has a releases section for this

**Comment by danbates2** [comment]
True. Noticed.
I've updated my branch and amended the doco. This Okay?

**Comment by danbates2** [comment]
v1.8.0 uses core v2.4.2 which is the most recent stable core for emonesp-master.

I'll change it to src/arduino-libs to avoid any confusion... done.

Do you want to include the emonupload tool in the doco now or when we next do a release of emonesp?

**Comment by glynhudson** [comment]
Thanks, that's great. 

There's no harm in mentioning emonupload now, it works fine for EmonESP, we've been using it since day 1 as a primary method of loading FW onto each EmonESP before they are shipped.

**Pull request merged**
