### PR TITLE
More Debug and Adafruit IO support

### PR DESCRIPTION
**Pull request by jeremypoulter**
Adafruit IO need feeds of the format username/f/feed so if you want to group the EmonESP feeds together you can now add a prefix to the feed name received from the EmonTX, for example, given the base topic of username/f and prefix of emonesp- the end topic woould be username/f/emonesp-P0 for the P0 feed.

Updated the read me to include info on how to enable the ESP's trace messages, this also needs a change to use src_build_flags rather than build_flags to pass the version number. The src_build_flags are just not passed to the libraries and only passed when building anything in src.

Added the ability to set the admin interface username and password.

Various changes to try to not fetch files in parallel as the ESP8266 (or rather the standard HTTP server library) can only handle one connection at a time.

Various bits of tidy-up that hopefully make it easier to follow the code.

### CODE REVIEW

**Comment by glynhudson** [comment]
Wow, lots of changes here, you've been busy! 
I'm probably not going to have a lot of time in the next 24hrs, heading to Manchester tomorrow if attend EcoHome lab. Here are my first impressions 

- 👍  `emoncms_publish` and `mqtt_loop` functions
- 👍  Wifi state variable name change
- 👍 Love the EEPROM write and read functions, much more efficient 

- Need to investigate how the Platformio debug build flags work. Looks interesting, although @TrystanLea who is also working on this uses ArduinoIDE to compile, will he still be able to see debug output when compiling the EmonESP code? I would like the code to also compile fine on ArduinoIDE

- I Don't quite understand the need for the change of build flag variable name. Happy to go with it as long as it does not disrupt the PlatformIO / Travis / OTA upload build setup [see blog post](https://blog.openenergymonitor.org/2016/06/esp8266-ota-update/)

- 👎 Not sure about the additional MQTT topic separator, I don't think Adafruit is [adhering to MQTT best practices](http://www.hivemq.com/blog/mqtt-essentials-part-5-mqtt-topics-best-practices). This seems to be a very Adafruit specific thing, I have not heard of other MQTT brokers requiring this. Using MQTT separators would make it difficult for other services such as openHAB, HomeAssistant or nodeRED the subscribe to a particular MQTT topic. IMO this is the point of MQTT to allow all services to link together. What advantage does using the MQTT broker have over other MQTT brokers or even running your own on a RaspberryPi. 

Sorry if I've missed some details, it;'s late and this is just fist impression. Very much appreciate you help. I'll get back to you once I've had a chance to test and review

**Comment by jeremypoulter** [comment]
> Need to investigate how the Platformio debug build flags work. Looks interesting, although @TrystanLea who is also working on this uses ArduinoIDE to compile, will he still be able to see debug output when compiling the EmonESP code? I would like the code to also compile fine on ArduinoIDE

The method I have documented there is essentially what the Arduino IDE is doing (finally something that the Arduino IDE actually does well ;-). All the menu options in the Arduino IDE just set #define, via the -D... command line options so there is no compatibility issues. This bit is (mostly) just documentation anyway.

> I Don't quite understand the need for the change of build flag variable name. Happy to go with it as long as it does not disrupt the PlatformIO / Travis / OTA upload build setup see blog post

To support the above I am essentially overriding the build_flags in platfomio.ini. So as the BUILD_TAB is only needed for src.ini and the debug options are needed for all the libraries etc it seemed that this was the easiest way to resolve the conflict. 

> :-1: Not sure about the additional MQTT topic separator, I don't think Adafruit is adhering to MQTT best practices. This seems to be a very Adafruit specific thing, I have not heard of other MQTT brokers requiring this. Using MQTT separators would make it difficult for other services such as openHAB, HomeAssistant or nodeRED the subscribe to a particular MQTT topic. IMO this is the point of MQTT to allow all services to link together. What advantage does using the MQTT broker have over other MQTT brokers or even running your own on a RaspberryPi.

Probably a bad description on my part, Adafruit is doing the same as any other MQTT broker. It is just that they expect a flat hierarchy once you put data into your account, eg the topics have to be of the format username/f/feed. So this is fine if you are happy with using the names EmonTX is kicking out but I wanted a way of grouping them with a prefix... oh wait... that is a much better way to fix it... morel of the story take a step back and look at the bigger picture ;-) I will update the PR with the option to set a feed name prefix, I may as well add the setting of the username/password as well. As this is mostly the same code that needs changing

**Comment by jeremypoulter** [comment]
I have made some changes, the stuff to support Adafruit is now the ability to add a prefix to the feed name, while I understand this is not necessarily best practice it should not affect any other MQTT brokers operation.

I also added setting the admin username/password.

**Comment by glynhudson** [comment]
Awesome 👍 

This looks great, I should have time to test and merge over this weekend. Thanks a lot for adding the username and password chaning feature.

**Pull request merged**
